import { h, render, Component } from "preact";

export default () => {
  return ["I write often about the web. Here's some stuff I've written:",
    <br />,
    <h2>A List Apart</h2>,
    [<strong>1. </strong>, <a href="https://alistapart.com/article/designing-for-research" rel="noopener">Designing for Research</a>],
    [<strong>2. </strong>, <a href="https://alistapart.com/article/considering-how-we-use-http2/" rel="noopener">Considering How We Use HTTP/2</a>],
    [<strong>3. </strong>, <a href="https://alistapart.com/article/using-http-2-responsibly-adapting-for-users/" rel="noopener">Using HTTP/2 Responsibly: Adapting for Users</a>],
    <br />,
    <h2>CSS-Tricks</h2>,
    [<strong>4. </strong>, <a href="https://css-tricks.com/help-users-save-data/" rel="noopener">Help Your Users `Save-Data`</a>],
    [<strong>5. </strong>, <a href="https://css-tricks.com/paint-timing-api/" rel="noopener">Using the Paint Timing API</a>],
    [<strong>6. </strong>, <a href="https://css-tricks.com/musings-on-http2-and-bundling/" rel="noopener">Musings on HTTP/2 and Bundling</a>],
    [<strong>7. </strong>, <a href="https://css-tricks.com/brotli-static-compression/" rel="noopener">Brotli and Static Compression</a>],
    [<strong>8. </strong>, <a href="https://css-tricks.com/cache-aware-server-push/" rel="noopener">Creating a Cache-aware HTTP/2 Server Push Mechanism</a>],
    [<strong>9. </strong>, <a href="https://css-tricks.com/using-webp-images/" rel="noopener">Using WebP Images</a>],
    [<strong>10. </strong>, <a href="https://css-tricks.com/font-display-masses/" rel="noopener">`font-display` for the Masses</a>],
    <br />,
    <h2>David Walsh Blog</h2>,
    [<strong>11. </strong>, <a href="https://davidwalsh.name/jpeg-compression-guetzli/" rel="noopener">JPEG Compression with Guetzli</a>],
    <br />,
    <h2>Google Web Fundamentals</h2>,
    [<strong>12. </strong>, <a href="https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/" rel="noopener">Replace Animated GIFS with Video</a>],
    [<strong>13. </strong>, <a href="https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data/" rel="noopener">Delivering Fast and Light Applicat ions with Save-Data*</a>],
    [<strong>14. </strong>, <a href="https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/" rel="noopener">Lazy Loading Images and Video</a>],
    [<strong>15. </strong>, <a href="https://developers.google.com/web/fundamentals/performance/why-performance-matters/" rel="noopener">Why Performance Matters</a>],
    <br />,
    <h2>Manning Publications</h2>,
    [<strong>16. </strong>, <a href="https://manning.com/books/web-performance-in-action?a_aid=webopt&a_bid=63c31090" rel="noopener">Web Performance in Action</a>],
    <br />,
    <h2>Net Magazine</h2>,
    [<strong>17. </strong>, <a href="https://www.creativebloq.com/how-to/4-essential-image-optimisation-tips" rel="noopener">4 Quick Image Optimization Tips</a>],
    [<strong>18. </strong>, <a href="https://www.creativebloq.com/how-to/5-tips-for-super-fast-css" rel="noopener">5 Tips for Super-fast CSS</a>],
    <br />,
    <h2>Planet Performance</h2>,
    [<strong>19. </strong>, <a href="https://calendar.perfplanet.com/2017/3-tips-for-faster-font-loading/" rel="noopener">3 Tips for Faster Font Loading</a>],
    [<strong>20. </strong>, <a href="https://calendar.perfplanet.com/2016/speed-versus-speed-to-market/" rel="noopener">Speed vs. Speed to Market</a>],
    <br />,
    <h2>Smashing Magazine</h2>,
    [<strong>21. </strong>, <a href="https://www.smashingmagazine.com/2017/04/guide-http2-server-push/" rel="noopener">A Comprehensive Guide to HTTP/2 Server Push</a>],
    [<strong>22. </strong>, <a href="https://www.smashingmagazine.com/2016/10/next-generation-server-compression-with-brotli/" rel="noopener">Next Generation Server Compression with Brotli</a>]
  ];
};
